services:
  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      # Pass the backend service name as the host for NEXT_PUBLIC_GOSERVER
      NEXT_PUBLIC_GOSERVER: "backend:8080"
      GOSERVER: "backend:8080"

networks:
  app-network:
    driver: bridge
